### ISSUE TITLE
Modification de lignes fichier Global.ini

### ISSUE THREAD

**Issue by FS-Pulsar** [SPEED0U/StarCitizenTranslations#14]
Salut !

Merci pour la traduction en Français. Quelques erreurs relevées 👍 

Ligne 67365 au lieu de "Lieu" mettre "Poser ici" lors de la mission de dépose de colis.
Ligne 67384 au lieu de "Coussins de toit" mettre "Plate-forme de toit"

![20231015_translation-fr_global_correction](https://github.com/SPEED0U/StarCitizenTranslations/assets/147974765/fae935fa-91b5-4ecd-b59a-fbcd45815dec)

**Comment by FS-Pulsar** [comment]
Autres lignes corrigées : 67415 vers 6767449, phrases plus appropriées.
![ligne-67415_67449_correction-traduction_global_ini](https://github.com/SPEED0U/StarCitizenTranslations/assets/147974765/6e5494f5-0fbc-41a9-9761-4d2b33fa1a0c)

**Comment by FS-Pulsar** [comment]
Correction des lignes 80 à 85 : Au lieu de "Plaidoyer" mettre "Forces de l'Ordre"

![20231015_correction_traduction-Advocacy](https://github.com/SPEED0U/StarCitizenTranslations/assets/147974765/40bc86d3-7403-4b43-a152-355889f5753b)

**Comment by FS-Pulsar** [comment]
Correction des lignes 97 à 101 

![20231015_correction_traduction-ViolentInmate](https://github.com/SPEED0U/StarCitizenTranslations/assets/147974765/1cf1a414-a4e0-47e9-ac11-7345f570d46a)

**Comment by SPEED0U** [comment]
Merci pour les suggestions, les changements ont été appliqués!
