### ISSUE TITLE
Centralize efforts

### ISSUE THREAD

**Issue by Dymerz** [SPEED0U/StarCitizenTranslations#2]
Dude it's huge, you work is amazing! 🚀

I made a repo to centralize all locales, whats about merging our work together? 🙂

Here is the repo: https://github.com/Dymerz/StarCitizen-Localization

**Comment by SPEED0U** [comment]
Thanks you!
I agree, you can put my FR translation on your repo :)

**Comment by Dymerz** [comment]
I meant, we could collaborate with each other and manage a single repository (the "_one to rule them all_"). I've created a GitHub Organization to help us better organize, If you're interested, let's discuss further!😄

https://github.com/StarCitizen-Localization
