### ISSUE TITLE
Proposition d'amélioration de la traduction

### ISSUE THREAD

**Issue by 0sryc** [SPEED0U/StarCitizenTranslations#5]
Bonjour,

Je vous soumet quelques améliorations pour la traduction, a prendre ou à laisser :) :

Numéro de ligne - texte actuel - texte de remplacement

Ligne **39850** => Matrice de communication => Satellite de communication
Ligne **39851** => Matrice de communication => Satellite de communication
Ligne **39852** => Matrice de communication => Satellite de communication
Ligne **39853** => Matrice de communication => Satellite de communication
Ligne **39854** => Matrice de communication => Satellite de communication
Ligne **39973** => Matrice de communication => Satellite de communication
Ligne **39974** => Matrice de communication => Satellite de communication
Ligne **39975** => Matrice de communication => Satellite de communication
Ligne **39976** => Matrice de communication => Satellite de communication
Ligne **40117** => Matrice de communication => Satellite de communication
Ligne **40118** => Matrice de communication => Satellite de communication
Ligne **40119** => Matrice de communication => Satellite de communication
Ligne **40199** => Matrice de communication => Satellite de communication
Ligne **40201** => Matrice de communication => Satellite de communication
Ligne **40202** => Matrice de communication => Satellite de communication
Ligne **42307** => Calibrer la matrice => Étalonnage du réseau
Ligne **42308** => Désactiver le tableau => Désactiver le réseau
Ligne **42306** => Activer le tableau => Activer le réseau
Ligne **42295** => Comm Array en ligne => Réseau de communication en ligne
Ligne **42293** => Tableau désactivé => Réseau désactivé
Ligne **42314** => Désactivation du tableau => Désactivation du réseau
Ligne **42294** => Comm Array est maintenant en ligne => Le réseau est maintenant en ligne
Ligne **42288** => Activation du tableau => Activation du réseau
Ligne **40502** => AVERTISSEMENT => DANGER

**Comment by SPEED0U** [comment]
Merci pour les suggestions!
