### ISSUE TITLE
Modif de ligne 

### ISSUE THREAD

**Issue by Ashleyrioth** [SPEED0U/StarCitizenTranslations#7]
med_Triage_Room=Chambre - ligne 58196
ui_interactor_open_ladder=Déployer l'échelle - ligne 67333

ui_interactor_lobby=Accueil - ligne 67319

C'est écrit "Pavé" à la place de "Pad"  pour les lignes suivante ligne 46049 : 

ui_interactor_pad_10=Pad 10 
ui_interactor_pad_11=Pad 11
ui_interactor_pad_12=Pad 12
ui_interactor_pad_13=Pad 13
ui_interactor_pad_14=Pad 14
ui_interactor_pad_15=Pad 15
ui_interactor_pad_16=Pad 16
ui_interactor_pad_17=Pad 17
ui_interactor_pad_18=Pad 18
ui_interactor_pad_19=Pad 19
ui_interactor_pad_20=Pad 20

ui_interactor_quick_seat_exit=Sortie rapide

ui_inventory_filter_category_name_armor_core=Torse

ui_interactor_IAE2950_Hall_02=Salle des Aegis
ui_interactor_IAE2950_Hall_03=Salle des Anvil
ui_interactor_IAE2950_Hall_04=Salle des Crusader
ui_interactor_IAE2950_Hall_08=Salle Origine

ça reste des détails

**Comment by SPEED0U** [comment]
Merci pour les suggestions!
